theme: minima

title: AuroraCodingForFun's personal  (will probably edit it later)
description: This is where I share cool stuff about my life, or not, we'll see
author: AuroraCodingForFun aka me
